using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BookLibrary.Api.Data.Migrations
{
    /// <inheritdoc />
    public partial class InitialLibrarySchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql("""
                    CREATE TABLE "Books" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Books" PRIMARY KEY,
                        "Title" text NOT NULL,
                        "Author" text NOT NULL,
                        "Isbn" text NOT NULL,
                        "Genre" text NOT NULL,
                        "PublishedYear" integer NOT NULL,
                        "IsAvailable" boolean NOT NULL
                    );

                    CREATE TABLE "Loans" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Loans" PRIMARY KEY,
                        "BookId" integer NOT NULL,
                        "BorrowerName" character varying(200) NOT NULL,
                        "BorrowedAt" timestamp with time zone NOT NULL,
                        "ReturnedAt" timestamp with time zone NULL,
                        CONSTRAINT "FK_Loans_Books_BookId" FOREIGN KEY ("BookId")
                            REFERENCES "Books" ("Id") ON DELETE CASCADE
                    );

                    CREATE TABLE "Reservations" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Reservations" PRIMARY KEY,
                        "BookId" integer NOT NULL,
                        "RequesterName" character varying(200) NOT NULL,
                        "ReservedAt" timestamp with time zone NOT NULL,
                        "IsActive" boolean NOT NULL,
                        CONSTRAINT "FK_Reservations_Books_BookId" FOREIGN KEY ("BookId")
                            REFERENCES "Books" ("Id") ON DELETE CASCADE
                    );

                    CREATE INDEX "IX_Loans_BookId" ON "Loans" ("BookId");
                    CREATE INDEX "IX_Reservations_BookId" ON "Reservations" ("BookId");
                    """);
                return;
            }

            if (ActiveProvider != "Microsoft.EntityFrameworkCore.Sqlite")
            {
                throw new InvalidOperationException($"Unsupported database provider: {ActiveProvider}");
            }

            if (ActiveProvider == "Microsoft.EntityFrameworkCore.Sqlite")
            {
                migrationBuilder.Sql("""
                    CREATE TABLE IF NOT EXISTS "Books" (
                        "Id" INTEGER NOT NULL CONSTRAINT "PK_Books" PRIMARY KEY AUTOINCREMENT,
                        "Title" TEXT NOT NULL,
                        "Author" TEXT NOT NULL,
                        "Isbn" TEXT NOT NULL,
                        "Genre" TEXT NOT NULL,
                        "PublishedYear" INTEGER NOT NULL,
                        "IsAvailable" INTEGER NOT NULL
                    );
                    """);
            }
            else
            {
                migrationBuilder.CreateTable(
                    name: "Books",
                    columns: table => new
                    {
                        Id = table.Column<int>(type: "INTEGER", nullable: false)
                            .Annotation("Sqlite:Autoincrement", true),
                        Title = table.Column<string>(type: "TEXT", nullable: false),
                        Author = table.Column<string>(type: "TEXT", nullable: false),
                        Isbn = table.Column<string>(type: "TEXT", nullable: false),
                        Genre = table.Column<string>(type: "TEXT", nullable: false),
                        PublishedYear = table.Column<int>(type: "INTEGER", nullable: false),
                        IsAvailable = table.Column<bool>(type: "INTEGER", nullable: false)
                    },
                    constraints: table =>
                    {
                        table.PrimaryKey("PK_Books", x => x.Id);
                    });
            }

            migrationBuilder.CreateTable(
                name: "Loans",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    BookId = table.Column<int>(type: "INTEGER", nullable: false),
                    BorrowerName = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    BorrowedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    ReturnedAt = table.Column<DateTime>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Loans", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Loans_Books_BookId",
                        column: x => x.BookId,
                        principalTable: "Books",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Reservations",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    BookId = table.Column<int>(type: "INTEGER", nullable: false),
                    RequesterName = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    ReservedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    IsActive = table.Column<bool>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Reservations", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Reservations_Books_BookId",
                        column: x => x.BookId,
                        principalTable: "Books",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Loans_BookId",
                table: "Loans",
                column: "BookId");

            migrationBuilder.CreateIndex(
                name: "IX_Reservations_BookId",
                table: "Reservations",
                column: "BookId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Loans");

            migrationBuilder.DropTable(
                name: "Reservations");

            migrationBuilder.DropTable(
                name: "Books");
        }
    }
}
